#!/usr/bin/env python3
"""Writes layout.conf for Machinedrum One: one tab per track, each with a real captured LCD screen
(the AMP/EFX page - vst/build/lcd/amp_fx_page.png, generated by tools/mdtrace/capture_screens.py, never
committed - see docs/FIRMWARE.md) as a decorative header, and all 12 of that track's params as knobs
below it, matching the real hardware's own AMD/EQF/EQG/FLTF/FLTW/FLTQ page order (gen_params.py's
FX_PARAMS) plus machine/vol/pan.

The 8 AMD..SRR knobs use `strip=`/`frames=128` filmstrips built from real bit-exact LCD capture
(tools/mdtrace/build_amp_fx_knob_strips.py - the Phase 2/4 dial-pointer atlases, see HANDOFF.md's
"Skin plan: the Monomodule way"), at `build/knobs/<fxkey>.png`; run that script before this one.
MACHINE/VOL/PAN/DIST keep the generic default knob look for now - MACHINE's own SYN-label picture
overlay (tools/mdtrace/gen_syn_label_overlays.py) isn't wired into this layout yet (needs the SYN1-8
params exposed first, blocked on "touched" tracking in engine.cpp - see HANDOFF.md)."""

FX_PARAMS = [("amd", "AMD"), ("amf", "AMF"), ("eqf", "EQF"), ("eqg", "EQG"), ("fltf", "FLTF"),
             ("fltw", "FLTW"), ("fltq", "FLTQ"), ("srr", "SRR"), ("dist", "DIST")]

lines = [
    "# Machinedrum One skin layout: one tab per track. The header image is the real Machinedrum's",
    "# own AMP/EFX parameter page, captured bit-exact from full-system emulation of the user's own",
    "# firmware (tools/mdtrace/capture_screens.py) - see HANDOFF.md \"the skin's foundation\". Never",
    "# committed itself (build/lcd/ is build output); this layout just references the path.",
    "style=td3",
    "theme_bg=17171a",
    "theme_panel=201f1e",
    "theme_line=3a3936",
    "theme_ink=d8d6ce",
    "theme_ink_dim=8a8880",
    "theme_accent=d9861f",
    "theme_accent_hi=f2a83c",
    "theme_knob_face=1c1c1c",
    "theme_knob_ring=3a3a3a",
    "theme_knob_dot=d9861f",
    "theme_lcd=141311",
    "theme_box=201f1e",
    "theme_btn_bg=121212",
    "theme_btn_text=f2f0e8",
    "",
]

for t in range(16):
    tab = "TRACK %d" % (t + 1)
    lines.append("[tab %s]" % tab)
    lines.append('art file=build/lcd/amp_fx_page.png x=340 y=88 w=600 h=300')
    lines.append('frame x=36 y=88 w=280 h=520 title="%s"' % tab)
    lines.append('knob cx=176 cy=180 r=40 label="MACHINE" key=track%d_machine' % t)
    lines.append('knob cx=100 cy=300 r=36 label="VOL" key=track%d_vol' % t)
    lines.append('knob cx=252 cy=300 r=36 label="PAN" key=track%d_pan' % t)
    keys = ["track%d_machine" % t, "track%d_vol" % t, "track%d_pan" % t]
    cols = [420, 570, 720, 870]
    rows = [420, 520]
    for i, (fxkey, fxlabel) in enumerate(FX_PARAMS):
        cx = cols[i % 4]
        cy = rows[i // 4] if i < 8 else 420  # 9th (dist) wraps to a 3rd row start
        if i == 8:
            cx, cy = cols[0], 600
        strip = ' strip=build/knobs/%s.png frames=128' % fxkey if i < 8 else ''
        lines.append('knob cx=%d cy=%d r=32 label="%s" key=track%d_%s%s' % (cx, cy, fxlabel, t, fxkey, strip))
        keys.append("track%d_%s" % (t, fxkey))
    lines.append('qlinks "%s" = %s' % (tab, ",".join(keys)))
    lines.append("")

lines.append("[tab GLOBAL]")
lines.append('knob cx=200 cy=300 r=40 label="TEMPO" key=tempo')
lines.append('knob cx=400 cy=300 r=40 label="MAX VOICES" key=max_voices')
lines.append('qlinks "GLOBAL" = tempo,max_voices')

open("layout.conf", "w").write("\n".join(lines) + "\n")
print("layout.conf: %d tabs" % 17)
